answer/urls.py
from django.urls import path

from . import views

app_name = 'answer'
urlpatterns = [
    path('<int:exam_id>/<int:question_id>/addanswer',
         views.add_answer, name="add_answer"),
    path('<int:exam_id>/<int:answer_id>/delete_answer',
         views.delete_answer, name="delete_answer"),
    path('<int:exam_id>/<int:answer_id>/edit_answer',
         views.edit_answer, name="edit_answer"),
]

course/urls.py
from django.urls import path

from . import views

app_name = 'course'
urlpatterns = [
    path('add', views.add_course, name="add_course"),
    path('<int:course_id>/edit', views.edit_course, name="edit_course"),
    path('<int:course_id>/delete',
         views.delete_course, name="delete_course"),
]

exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'

urlpatterns = [
    path('<int:course_id>/exam/add', views.add_exam, name="add_exam"),
    path('<int:exam_id>/', views.get_exam, name="get_exam"),
    path('<int:exam_id>/edit', views.edit_exam, name="edit_exam"),
    path('<int:exam_id>/delete', views.delete_exam, name="delete_exam"),
]

latex2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studysystem.urls'), name="home_page"),
    path('course/', include('course.urls'), name="course_page"),
    path('exam/', include('exam.urls'), name="exam_page"),
    path('question/', include('question.urls'), name="question_page"),
    path('answer/', include('answer.urls'), name="answer_page"),
]

question/urls.py
from django.urls import path

from . import views

app_name = 'question'
urlpatterns = [
    path('<int:exam_id>/addquestion', views.add_question,
         name="add_question"),
    path('<int:exam_id>/<int:question_id>/delete_question',
         views.delete_question, name="delete_question"),
    path('<int:exam_id>/<int:question_id>/edit_question',
         views.edit_question, name="edit_question"),
]

studysystem/urls.py
from django.urls import path

from . import views

app_name = 'study'
urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('student/get_student/<int:student_id>/<int:course_id>/delete', views.delete_course, name="delete_course"),

    path('student/add', views.add_student, name="add_student"),
    path('student/get_students', views.get_students, name="get_students"),
    path('student/get_student/<int:student_id>', views.get_student, name="get_student"),
    path('student/get_student/<int:student_id>/delete', views.delete_student, name="delete_student"),

    path('generate/<int:exam_id>/', views.generate_page,
         name="generate_page"),
]

exam/models.py
from django.db import models


# Create your models here.
class Exam(models.Model):
    name_of_exam = models.CharField(max_length=50)
    course = models.ForeignKey('course.Course', on_delete=models.CASCADE)

    def __str__(self):
        return self.name_of_exam

    def __repr__(self):
        return self.name_of_exam

studysystem/models.py
from django.db import models


class Student(models.Model):
    id_of_student = models.CharField(max_length=100)
    name = models.CharField(max_length=100, default="")
    surname = models.CharField(max_length=100, default="")
    course = models.ManyToManyField('course.Course', null=True)

    def __str__(self):
        return self.name

studysystem/views.py
import subprocess
import os
import re
import pyqrcode

from django.views.static import serve
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.views.generic import CreateView
from exam.models import Exam
from course.models import Course
from studysystem.models import Student

from latex2.settings import BASE_DIR

# Create your views here.


def home_page(request):
    c = Course.objects.all()
    context = {"courses": c}
    return render(request, 'home.html', context)


def get_students(request):
    students = Student.objects.all()
    context = {"students": students}
    return render(request, "get_students.html", context)


def get_student(request, student_id):
    student = Student.objects.filter(pk=student_id)
    courses = Course.objects.all()
    context = {"student": student, "courses": courses}
    if request.POST:
        number = request.POST.get('number', "error")
        name = request.POST.get('name', "error")
        surname = request.POST.get('surname', "error")
        if not number == "error":
            student = Student.objects.get(pk=student_id)
            student.number = number
            student.name = name
            student.surname = surname
            student.save()
            return redirect("study:get_students")

        else:
            id = request.POST.get('dropdown_courses', "error")
            if not id == "error":
                student = Student.objects.get(pk=student_id)
                course = Course.objects.get(pk=id)
                student.course.add(course)
        return redirect("study:get_student", student_id)
    return render(request, "students/get_student.html", context)


def add_student(request):
    if request.POST:
        number = request.POST.get('number', 'error')
        name = request.POST.get('name', 'error')
        surname = request.POST.get('surname', 'error')

        if not (number or name or surname) == "error":
            Student.objects.create(id_of_student=number,
                                   name=name,
                                   surname=surname)

        return redirect("study:get_students")
    return render(request, "students/add_student.html")


def delete_student(request, student_id):
    Student.objects.filter(pk=student_id).delete()
    return redirect("study:get_students")


def delete_course(request, student_id, course_id):
    student = Student.objects.get(pk=student_id)
    course = Course.objects.get(pk=course_id)
    student.course.remove(course)
    return redirect("study:get_student", student_id)


def generate_page(request, exam_id):
    course = Course.objects.get(exam=exam_id)
    students = Student.objects.filter(course=course)
    context = {"students": students}

    if request.POST:
        student_id = request.POST.get("dropdown_students", "error")
        if not student_id == "error":
            # Just a file to be based on something
            with open('latex_sample.tex') as f:
                file = f.read()
            # Template of answers
            with open('closed_answer_template.txt', 'r') as answer_temp:
                answer_tempalte = answer_temp.read()

            with open('open_answer_template.txt', 'r') as open_answer_template:
                open_answer_template = open_answer_template.read()

            exam = Exam.objects.get(pk=exam_id)
            questions = exam.question_set.all()

            # Create some temporary file and create there questions with
            # answers
            with open('temp.txt', 'w') as f:
                for num, quest in enumerate(questions):
                    num += 1

                    # Writing questions
                    f.write("\n\question {}\n".format(quest))
                    f.write(r"\n")
                    if quest.answer_set.all():
                        # Writing circle answers
                        new_anwers = re.sub(
                            "_Number_", str(num), answer_tempalte)

                        file = re.sub(r"%paste_here_answers", new_anwers, file)

                        f.write(r"\\begin{oneparchoices}")
                        for answer in quest.answer_set.all():
                            f.write("\n\choice {} \n".format(answer.answer))
                        f.write(r"\\end{oneparchoices} %question" + str(num))
                        f.write(r"\n%paste_here_question")
                    else:
                        f.write(r"\n\\begin{solutionorlines}[0.5in]\n" +
                                r"\\end{solutionorlines}")
                        new_anwers = re.sub("_Number_", str(
                            num), open_answer_template)
                        file = re.sub(r"%paste_here_answers", new_anwers, file)

            # Reading that temp file
            with open('temp.txt', 'r') as f:
                tempfile = f.read()

            # Writing to a new file
            file_name = exam.name_of_exam
            filename = file_name + ".tex"
            with open(filename, 'w') as f:
                f.write(re.sub(r'%paste_here_question', tempfile, file))
            student = Student.objects.get(pk=student_id)
            qr = pyqrcode.create(student.id_of_student)
            qr.eps('QRCode.eps')

            cmd = ['pdflatex', '-interaction', 'nonstopmode', filename]
            proc = subprocess.Popen(cmd)
            proc.communicate()
            try:
                os.remove("{}.aux".format(file_name))
                os.remove("{}.log".format(file_name))
                os.remove("{}.tex".format(file_name))
                os.remove("temp.txt")
            except Exception as e:
                pass

            path_to_file = BASE_DIR + "\\" + file_name + ".pdf"
            return serve(request, os.path.basename(path_to_file),
                         os.path.dirname(path_to_file))
            # return redirect('get_exam', exam_id)
    return render(request, 'generate.html', context)

studysystem/templates/add.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
          <h1 class="display-3 centered">{{title}}</h1>
          <form method="POST">
            {%csrf_token%}
            <div class="input-group mb-3">
                  <input type="text" class="form-control" aria-describedby="basic-addon2" name="input_data">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Send</button>
                  </div>
            </div>
          </form>
    </div>
{%endblock%}

studysystem/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/site.css' %}" rel="stylesheet" media="screen">
    <meta charset="UTF-8">
    <title>{%block title%}{% endblock %}</title>
</head>
<body>
    <div class="container">
      <header class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'study:home_page'%}">Home <span class="sr-only">(current)</span></a>
            </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'study:get_students'%}">Students</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">About</a>
              </li>
            </ul>
          </nav>
          <h3 class="text-muted">LaTeX project</h3>
        </header>

    {% block content %}
    {% endblock %}
    <footer class="footer">
        <p>© Bekzat Shayakhmetov 2018</p>
    </footer>

    </div> <!-- /container -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

studysystem/templates/edit.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
        <h1 class="display-4 centered">{{title}}</h1>
        <br>
        <form action="" method="POST">
          {% csrf_token %}
            <div class="input-group mb-3">
                  <input type="text" class="form-control" value="{{value}}" aria-describedby="basic-addon2" name="input_data">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Send</button>
                  </div>
            </div>
        </form>
    </div>
{%endblock%}

studysystem/templates/generate.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
        <form action="" method="POST">
             {%csrf_token%}
             <p>Please select a student to generate the special file!</p>
            <select name="dropdown_students" id="">
                {%for student in students%}
                    <option value="{{student.id}}" name="student">{{student.name}} {{student.surname}}</option>
                {%endfor%}
            </select>
                <button class="btn btn-primary" type="submit">Generate</button>
        </form>
    </div>
{%endblock%}

studysystem/templates/get_exam.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
            {%for exam in examination%}
                <h1 class="display-3 centered">{{exam}}</h1>
                <br>
                <p class="lead centered">You can <a href="{%url 'study:generate_page' exam.id%}">generate</a> LaTeX file from this exam page</p>

                <p class="lead">You can add questions <a href="{%url 'question:add_question' exam.id%}">here</a></p>


                {%for question in exam.question_set.all%}
                    <p class="lead">{{forloop.counter}}. {{question}} | <a href="{%url 'question:edit_question' exam.id question.id%}"> Edit</a><a href="{%url 'question:delete_question' exam.id question.id%}"> Delete  </a> | <a href="{%url 'answer:add_answer' exam.id question.id%}">  Add answer</a></p>

                    {%for answers in question.answer_set.all%}
                        <ul>
                            <li>
                                <p>{{answers.answer}} | <a href="{%url 'answer:edit_answer' exam.id answers.id%}"> Edit</a> | <a href="{%url 'answer:delete_answer' exam.id answers.id %}">Delete</a> </p>
                            </li>
                        </ul>
                    {%endfor%}
                {%endfor%}

            {%endfor%}
    </div>
{%endblock%}

studysystem/templates/get_students.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
        {%if students%}
                <h1 class="display-3 centered">List of students</h1>
                <p class="lead">You can add students <a href="{%url 'study:add_student'%}">here</a></p>
            {%for student in students%}
                <br>
                <ul>
                    <li><a href="{%url 'study:get_student' student.id%}">{{student.name}} {{student.surname}}</a> | <a href="{%url 'study:delete_student' student.id%}">Delete</a></li>
                </ul>
            {%endfor%}
        {%else%}
        <p class="lead">No students! You can add students <a href="{%url 'study:add_student'%}">here</a></p>
        {%endif%}
    </div>
{%endblock%}

studysystem/templates/home.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
          <h1 class="display-3 centered">LaTeX creator</h1>
          {%if courses%}
            <p class="lead">Here is the List of your courses: </p>
           <p class="lead">You can create courses <a href="{% url 'course:add_course' %}">here</a></p>
            {%for course in courses%}
                <p class="lead">{{forloop.counter}}. {{course}} course | <a href="{%url 'course:edit_course' course.id%}"> Edit </a> <a href="{%url 'course:delete_course' course.id%}"> Delete</a> | <a href="{%url 'exam:add_exam' course.id%}">Add Exam</a></p>
                {%if course.exam_set.all%}
                  <p class="lead small">{{course}}'s exams list:</p>
                    {% for exam in course.exam_set.all%}
                        <ul>
                            <li>
                              <p><a href="{%url 'exam:get_exam' exam.id %}">{{exam}}</a> | <a href="{%url 'exam:edit_exam' exam.id%}">Edit </a> <a href="{%url 'exam:delete_exam' exam.id%}"> Delete</a></p>
                            </li>
                        </ul>
                    {%endfor%}
                    {%else%}
                      <p class="lead small">No exams for {{course}}</p>
                  {%endif%}
            {%endfor%}
          {%else%}
           <p class="lead">There are no courses. You can create it <a href="{% url 'course:add_course' %}">now</a></p>
          {%endif%}
    </div>
{%endblock%}