exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'

urlpatterns = [
    path('<int:course_id>/exam/add', views.add_exam, name="add_exam"),
    path('<int:exam_id>/', views.get_exam, name="get_exam"),
    path('<int:exam_id>/edit', views.edit_exam, name="edit_exam"),
    path('<int:exam_id>/delete', views.delete_exam, name="delete_exam"),
]

latex2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studysystem.urls'), name="home_page"),
    path('course/', include('course.urls'), name="course_page"),
    path('exam/', include('exam.urls'), name="exam_page"),
    path('question/', include('question.urls'), name="question_page"),
    path('answer/', include('answer.urls'), name="answer_page"),
]

studysystem/urls.py
from django.urls import path

from . import views

app_name = 'study'
urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('student/get_student/<int:student_id>/<int:course_id>/delete', views.delete_course, name="delete_course"),

    path('student/add', views.add_student, name="add_student"),
    path('student/get_students', views.get_students, name="get_students"),
    path('student/get_student/<int:student_id>', views.get_student, name="get_student"),
    path('student/get_student/<int:student_id>/delete', views.delete_student, name="delete_student"),

    path('generate/<int:exam_id>/', views.generate_page,
         name="generate_page"),
]

studysystem/models.py
from django.db import models


class Student(models.Model):
    id_of_student = models.CharField(max_length=100)
    name = models.CharField(max_length=100, default="")
    surname = models.CharField(max_length=100, default="")
    course = models.ManyToManyField('course.Course', null=True)

    def __str__(self):
        return self.name

studysystem/views.py
import subprocess
import os
import re
import pyqrcode

from django.views.static import serve
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.views.generic import CreateView
from exam.models import Exam
from course.models import Course
from studysystem.models import Student

from latex2.settings import BASE_DIR

# Create your views here.


def home_page(request):
    c = Course.objects.all()
    context = {"courses": c}
    return render(request, 'home.html', context)


def get_students(request):
    students = Student.objects.all()
    context = {"students": students}
    return render(request, "get_students.html", context)


def get_student(request, student_id):
    student = Student.objects.filter(pk=student_id)
    courses = Course.objects.all()
    context = {"student": student, "courses": courses}
    if request.POST:
        number = request.POST.get('number', "error")
        name = request.POST.get('name', "error")
        surname = request.POST.get('surname', "error")
        if not number == "error":
            student = Student.objects.get(pk=student_id)
            student.number = number
            student.name = name
            student.surname = surname
            student.save()
            return redirect("study:get_students")

        else:
            id = request.POST.get('dropdown_courses', "error")
            if not id == "error":
                student = Student.objects.get(pk=student_id)
                course = Course.objects.get(pk=id)
                student.course.add(course)
        return redirect("study:get_student", student_id)
    return render(request, "students/get_student.html", context)


def add_student(request):
    if request.POST:
        number = request.POST.get('number', 'error')
        name = request.POST.get('name', 'error')
        surname = request.POST.get('surname', 'error')

        if not (number or name or surname) == "error":
            Student.objects.create(id_of_student=number,
                                   name=name,
                                   surname=surname)

        return redirect("study:get_students")
    return render(request, "students/add_student.html")


def delete_student(request, student_id):
    Student.objects.filter(pk=student_id).delete()
    return redirect("study:get_students")


def delete_course(request, student_id, course_id):
    student = Student.objects.get(pk=student_id)
    course = Course.objects.get(pk=course_id)
    student.course.remove(course)
    return redirect("study:get_student", student_id)


def generate_page(request, exam_id):
    course = Course.objects.get(exam=exam_id)
    students = Student.objects.filter(course=course)
    context = {"students": students}

    if request.POST:
        student_id = request.POST.get("dropdown_students", "error")
        if not student_id == "error":
            # Just a file to be based on something
            with open('latex_sample.tex') as f:
                file = f.read()
            # Template of answers
            with open('closed_answer_template.txt', 'r') as answer_temp:
                answer_tempalte = answer_temp.read()

            with open('open_answer_template.txt', 'r') as open_answer_template:
                open_answer_template = open_answer_template.read()

            exam = Exam.objects.get(pk=exam_id)
            questions = exam.question_set.all()

            # Create some temporary file and create there questions with
            # answers
            with open('temp.txt', 'w') as f:
                for num, quest in enumerate(questions):
                    num += 1

                    # Writing questions
                    f.write("\n\question {}\n".format(quest))
                    f.write(r"\n")
                    if quest.answer_set.all():
                        # Writing circle answers
                        new_anwers = re.sub(
                            "_Number_", str(num), answer_tempalte)

                        file = re.sub(r"%paste_here_answers", new_anwers, file)

                        f.write(r"\\begin{oneparchoices}")
                        for answer in quest.answer_set.all():
                            f.write("\n\choice {} \n".format(answer.answer))
                        f.write(r"\\end{oneparchoices} %question" + str(num))
                        f.write(r"\n%paste_here_question")
                    else:
                        f.write(r"\n\\begin{solutionorlines}[0.5in]\n" +
                                r"\\end{solutionorlines}")
                        new_anwers = re.sub("_Number_", str(
                            num), open_answer_template)
                        file = re.sub(r"%paste_here_answers", new_anwers, file)

            # Reading that temp file
            with open('temp.txt', 'r') as f:
                tempfile = f.read()

            # Writing to a new file
            file_name = exam.name_of_exam
            filename = file_name + ".tex"
            with open(filename, 'w') as f:
                f.write(re.sub(r'%paste_here_question', tempfile, file))
            student = Student.objects.get(pk=student_id)
            qr = pyqrcode.create(student.id_of_student)
            qr.eps('QRCode.eps')

            cmd = ['pdflatex', '-interaction', 'nonstopmode', filename]
            proc = subprocess.Popen(cmd)
            proc.communicate()
            try:
                os.remove("{}.aux".format(file_name))
                os.remove("{}.log".format(file_name))
                os.remove("{}.tex".format(file_name))
                os.remove("temp.txt")
            except Exception as e:
                pass

            path_to_file = BASE_DIR + "\\" + file_name + ".pdf"
            return serve(request, os.path.basename(path_to_file),
                         os.path.dirname(path_to_file))
            # return redirect('get_exam', exam_id)
    return render(request, 'generate.html', context)

studysystem/templates/students/add_student.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
          <h1 class="display-3 centered">Add a student</h1>
          <form method="POST">
            {%csrf_token%}
                  <label for="number">Number: </label>
                  <input type="text" class="form-control" name="number" id="number"> <br>

                   <label for="name">Name: </label>
                   <input type="text" class="form-control" name="name" id="name"> <br>

                   <label for="surname">Surname: </label>
                   <input type="text" class="form-control" aria-describedby="basic-addon2" name="surname" id="surname">

                  <div class="input-group-append">
                    <br><button class="btn btn-primary" type="submit">Send</button>
                  </div>
          </form>
    </div>
{%endblock%}

studysystem/templates/students/get_student.html
{%extends 'base.html'%}

{%block content%}
    <div class="jumbotron">
        {%if student%}
                <h1 class="display-3 centered">Info of a student</h1>
                <br>
                <ul>
            {%for s in student%}
                <form action="" method="POST">
                    {%csrf_token%}
                    <p>ID number:<input type="text" class="form-control" name="number" value="{{s.id_of_student}}"></p>
                    <p>First Name:  <input type="text" class="form-control" name="name" value="{{s.name}}"></p>
                    <p>Last Name: <input type="text" class="form-control" name="surname" value="{{s.surname}}"></p>
                    <button class="btn btn-primary" type="submit">Edit</button>
                </form>
                <br>

            <p class="lead">Courses of the student</p>
                {%for c in s.course.all%}
                    <ul>
                        <li>{{c.name_of_course}} | <a href="{%url 'study:delete_course' s.id c.id%}"> Delete</a></li>
                    </ul>
                {%endfor%}
            <p class="lead">You can add courses </p>
            {%endfor%}
            <form action="" method="POST">
                 {%csrf_token%}
                <select name="dropdown_courses" id="">
                    {%for course in courses%}
                        <option value="{{course.id}}" name="course">{{course.name_of_course}}</option>
                    {%endfor%}
                </select>
                    <button class="btn btn-primary" type="submit">Add course</button>
            </form>

        {%else%}
        <p class="lead">No students! You can add students <a href="{%url 'study:add_student'%}">here</a></p>
        {%endif%}
    </div>
{%endblock%}